name: Django apiTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# on:
#   schedule:
#     - cron: '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10,3.11]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Flake Tests
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django testing
      run: |
        python3 manage.py test
